version: '2'
services:
  mongo:
    container_name: mongo
    image:mongo:3.7.7-jessie
    volumes:
      - ./mongodata:/data/db
    command: redis-server --appendonly yes
    ports:
      -  27017:27017